name: Java CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Java + Loom early access build
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: setup
        uses: oracle-actions/setup-java@v1
        with:
          website: jdk.java.net
          release: 19
          version: 19.ea.32-open
      - name: Build with Maven Wrapper
        run: ./mvnw clean verify
